dependencies {
    implementation libs.springBootWeb
    implementation libs.springBootActuator
    implementation libs.springCloudEurekaServer
    implementation libs.springCloudAdminStarterServer
    implementation libs.log4jApi
    implementation libs.log4jCore
    implementation libs.log4jSlf4jImpl
}