plugins {
    id 'java'
    id 'java-library'
}

ext {
    versions = [
            springBoot: '3.0.13'
    ]

    libs = [
            springBootWeb: "org.springframework.boot:spring-boot-starter-web:${versions.springBoot}"
    ]
}

allprojects {
    group = 'com.buyukozkan'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}
