server:
  port: 9591

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:9999}/${POSTGRES_DB:Micro_AccountServiceDB}
    username: ${POSTGRES_USER:fintech}
    password: ${POSTGRES_PASSWORD:fintech123}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}


keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://${KEYCLOAK_HOST:127.0.0.1}:8180}
  realm: master
  admin-username: ${KEYCLOAK_ADMIN:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  token-url: ${KEYCLOAK_SERVER_URL:http://${KEYCLOAK_HOST:127.0.0.1}:8180}/realms/master/protocol/openid-connect/token
  client-id: account-service
  client-secret: ${KEYCLOAK_CLIENT_SECRET:admin}
